POST {{host}}/api/collections
Content-Type: application/json
Accept: application/json

{}

###

GET {{host}}/api/collections/6defc752-2ca5-44c7-b70b-7a800717b3a9
Accept: application/json


###

PUT {{host}}/api/collections/6defc752-2ca5-44c7-b70b-7a800717b3a9
Accept: application/json
Authorization: 261f0f90-938e-4c5e-a55f-43848ac2517b
Content-Type: application/json

{
  "collectionId": "6defc752-2ca5-44c7-b70b-7a800717b3a9",
  "initialImageId": "Basis",
  "title": "Sample Collection",
  "images": [
    {
      "imageId": "Basis",
      "title": "Basis",
      "src": "/Basis.jpg",
      "links": [
        {
          "imageId": "Bedeutung",
          "rectangle": {
            "percentageWidth": 9.078014184397164,
            "percentageHeight": 7.0962319151599695,
            "percentageX": 21.134751773049647,
            "percentageY": 19.55577015934331
          }
        }
      ]
    },
    {
      "imageId": "Bedeutung",
      "title": "Bedeutung",
      "src": "/Bedeutung.jpg",
      "links": []
    }
  ]
}
